name: github-desktop
version: latest
version-script: cat $SNAPCRAFT_STAGE/version
summary: Extend your GitHub workflow beyond your browser with GitHub Desktop
description: |
 Extend your GitHub workflow beyond your browser with our Desktop,
 completely redesigned with Electron. Get a unified cross-platform
 experience that's completely open source and ready to customize.

grade: stable
confinement: strict

parts:
  github-desktop:
    plugin: nil
    override-build: |
      snapcraftctl build
      # Get the latest releases json
      echo "Get GitHub releases..."
      wget --quiet https://api.github.com/repos/shiftkey/desktop/releases -O releases.json
      # Get the version from the tag_name and the download URL.
      VERSION=$(jq . releases.json | grep tag_name | cut -d'"' -f4 | sed s'/release-//' | head -n 1)
      DEB_URL=$(grep browser_download releases.json | grep "${VERSION}" | grep deb | cut -d'"' -f4)
      DEB=$(basename "${DEB_URL}")
      echo "Downloading ${DEB_URL}..."
      wget --quiet "${DEB_URL}" -O "${SNAPCRAFT_PART_INSTALL}/${DEB}"
      echo "Unpacking ${DEB}..."
      dpkg -x "${SNAPCRAFT_PART_INSTALL}/${DEB}" ${SNAPCRAFT_PART_INSTALL}
      rm -f releases.json 2>/dev/null
      rm -f "${SNAPCRAFT_PART_INSTALL}/${DEB}" 2>/dev/null
      echo $VERSION > $SNAPCRAFT_STAGE/version

      # Rename the .desktop file to something sensible.
      mv ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/desktop.desktop ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/github-desktop.desktop
      # Correct path to icon.
      sed -i 's|Icon=desktop|Icon=/usr/share/icons/hicolor/256x256/apps/desktop\.png|g' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/github-desktop.desktop
    after:
      - desktop-gtk2
    build-packages:
      # GitHub Desktop debs are only available for amd64.
      # Fail builds on other architectures
      - on amd64:
        - jq
        - wget
      - else fail
    stage-packages:
      - git
      - gnupg2
      - libasound2
      - libgconf2-4
      - libgl1-mesa-glx
      - libglu1-mesa
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6
      - openssh-client

apps:
  github-desktop:
    command: bin/desktop-launch $SNAP/opt/GitHubDesktop/desktop
    desktop: usr/share/applications/github-desktop.desktop
    # Correct the TMPDIR path for Chromium Framework/Electron to ensure
    # libappindicator has readable resources.
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - browser-support
      - desktop
      - desktop-legacy
      - gpg-keys
      - gsettings
      - home
      - mount-observe
      - network
      - opengl
      - pulseaudio
      - ssh-keys
      - unity7
      - wayland
      - x11
