name: github-desktop
version: 1.0.4-beta0
summary: Extend your GitHub workflow beyond your browser with GitHub Desktop
description: |
 Extend your GitHub workflow beyond your browser with our Desktop,
 completely redesigned with Electron. Get a unified cross-platform
 experience that's completely open source and ready to customize.

grade: stable
confinement: strict

parts:
  github-desktop:
    plugin: dump
    source: https://github.com/gengjiawen/desktop/releases/download/v1.0.4-beta0/desktop_1.0.4-beta0_amd64.deb
    source-type: deb
    # Correct path to icon.
    # Clear the execstack - https://forum.snapcraft.io/t/snap-and-executable-stacks/1812
    # execstack --clear-execstack opt/GithubDesktop/desktop
    prepare: |
      sed -i 's|Icon=desktop|Icon=/usr/share/icons/hicolor/256x256/apps/desktop\.png|g' usr/share/applications/desktop.desktop
    after:
      - desktop-gtk2
    build-packages:
      - execstack
    stage-packages:
      - libasound2
      - libgconf2-4
      - libgl1-mesa-glx
      - libglu1-mesa
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6

apps:
  github-desktop:
    command: bin/desktop-launch $SNAP/opt/GithubDesktop/desktop
    desktop: usr/share/applications/desktop.desktop
    # Correct the TMPDIR path for Chromium Framework/Electron to ensure
    # libappindicator has readable resources.
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - bluez
      - browser-support
      - gsettings
      - home
      - mount-observe
      - network
      - opengl
      - pulseaudio
      - unity7
      - wayland
      - x11
